### ISSUE TITLE
android multiview plugin demo video

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-plugin-multiview#41]
Produce a short screen capture of the demo app passing data from js->native->newView->js and back

**Comment by purplecabbage** [comment]
Team only link.
https://phonegap.slack.com/files/sterling/F3BPJ42AC/androiddemo.mov

**Comment by purplecabbage** [comment]
@sterling, please re-post your video here with a public link.  You can choose whether you want to use YouTube or DropBox or something else.

**Comment by sterling** [comment]
@purplecabbage wrong sterling ;)

**Comment by purplecabbage** [comment]
Sorry @sterling, I meant @sterlingann !
